language: php

php: 
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - LVERSION="4.1.*"
  - LVERSION="4.2.*"
  - LVERSION="4.3.*@dev"

before_install:
  - composer require illuminate/database:${LVERSION} illuminate/support:${LVERSION} --no-update

install: composer install --dev --prefer-dist

script: phpunit
